### ISSUE TITLE
Installation failed on OSX 10.12.5:

### ISSUE THREAD

**Issue by gastoncesarf** [Farama-Foundation/ViZDoom#251]
I executed `pip3 install .` but I get an error:

```
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-1xpigfnq-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7flo1mky-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-1xpigfnq-build/
```

Here is the complete log (I suppose that is related with boost or cmake):

```
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from vizdoom==1.1.3)
Installing collected packages: vizdoom
  Running setup.py install for vizdoom ... error
    Complete output from command /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-1xpigfnq-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7flo1mky-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    -- The C compiler identification is AppleClang 9.0.0.9000037
    -- The CXX compiler identification is AppleClang 9.0.0.9000037
    -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
    -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Warning at /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:554 (message):
      Imported targets and dependency information not available for Boost version
      (all versions older than 1.33)
    Call Stack (most recent call first):
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:894 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:1525 (_Boost_MISSING_DEPENDENCIES)
      CMakeLists.txt:90 (find_package)
    
    
    CMake Warning at /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:554 (message):
      Imported targets and dependency information not available for Boost version
      (all versions older than 1.33)
    Call Stack (most recent call first):
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:894 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:1525 (_Boost_MISSING_DEPENDENCIES)
      CMakeLists.txt:90 (find_package)
    
    
    CMake Warning at /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:554 (message):
      Imported targets and dependency information not available for Boost version
      (all versions older than 1.33)
    Call Stack (most recent call first):
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:894 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:1525 (_Boost_MISSING_DEPENDENCIES)
      CMakeLists.txt:90 (find_package)
    
    
    CMake Warning at /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:554 (message):
      Imported targets and dependency information not available for Boost version
      (all versions older than 1.33)
    Call Stack (most recent call first):
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:894 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:1525 (_Boost_MISSING_DEPENDENCIES)
      CMakeLists.txt:90 (find_package)
    
    
    CMake Warning at /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:554 (message):
      Imported targets and dependency information not available for Boost version
      (all versions older than 1.33)
    Call Stack (most recent call first):
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:894 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:1525 (_Boost_MISSING_DEPENDENCIES)
      CMakeLists.txt:90 (find_package)
    
    
    CMake Warning at /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:554 (message):
      Imported targets and dependency information not available for Boost version
      (all versions older than 1.33)
    Call Stack (most recent call first):
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:894 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:1525 (_Boost_MISSING_DEPENDENCIES)
      CMakeLists.txt:90 (find_package)
    
    
    CMake Warning at /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:554 (message):
      Imported targets and dependency information not available for Boost version
      (all versions older than 1.33)
    Call Stack (most recent call first):
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:894 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:1525 (_Boost_MISSING_DEPENDENCIES)
      CMakeLists.txt:90 (find_package)
    
    
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - found
    -- Found Threads: TRUE
    CMake Error at /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:1902 (message):
      Unable to find the requested Boost libraries.
    
      Unable to find the Boost header files.  Please set BOOST_ROOT to the root
      directory containing Boost or BOOST_INCLUDEDIR to the directory containing
      Boost's headers.
    Call Stack (most recent call first):
      CMakeLists.txt:90 (find_package)
    
    
    CMake Deprecation Warning at cmake_modules/CreateLaunchers.cmake:48 (cmake_policy):
      The OLD behavior for policy CMP0026 will be removed from a future version
      of CMake.
    
      The cmake-policies(7) manual explains that the OLD behaviors of all
      policies are deprecated and that a policy should be set to OLD only under
      specific short-term circumstances.  Projects should be ported to the NEW
      behavior and not rely on setting a policy to OLD.
    Call Stack (most recent call first):
      src/vizdoom/CMakeLists.txt:13 (include)
    
    
    -- Found BZip2: /usr/lib/libbz2.dylib (found version "1.0.6")
    -- Looking for BZ2_bzCompressInit
    -- Looking for BZ2_bzCompressInit - found
    -- Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
    -- Found ZLIB: /usr/local/lib/libz.dylib (found version "1.2.8")
    -- Could NOT find GME (missing: GME_LIBRARIES GME_INCLUDE_DIR)
    -- Using system zlib
    -- Using internal jpeg library
    -- Using system bzip2 library
    -- Using internal gme library
    -- Performing Test HAVE_NO_ARRAY_BOUNDS
    -- Performing Test HAVE_NO_ARRAY_BOUNDS - Success
    -- Looking for strdup
    -- Looking for strdup - found
    -- Looking for strndup
    -- Looking for strndup - found
    -- Looking for sys/types.h
    -- Looking for sys/types.h - found
    -- Looking for stdint.h
    -- Looking for stdint.h - found
    -- Looking for stddef.h
    -- Looking for stddef.h - found
    -- Check size of char
    -- Check size of char - done
    -- Check size of short
    -- Check size of short - done
    -- Check size of int
    -- Check size of int - done
    -- Check size of long
    -- Check size of long - done
    -- /usr/include
    -- /usr/include
    -- /tmp/pip-1xpigfnq-build/src/vizdoom/lzma/C
    -- Looking for itoa
    -- Looking for itoa - not found
    -- Performing Test DUMB_CAN_USE_SSE
    -- Performing Test DUMB_CAN_USE_SSE - Success
    -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE)
    -- Found SDL2: /usr/local/lib/libSDL2main.a;/usr/local/lib/libSDL2.dylib;-framework Cocoa
    -- Found OpenAL: /System/Library/Frameworks/OpenAL.framework
    -- Could not find FMOD include files
    -- Could NOT find SndFile (missing: SNDFILE_LIBRARY SNDFILE_INCLUDE_DIR)
    -- Could NOT find MPG123 (missing: MPG123_LIBRARIES MPG123_INCLUDE_DIR)
    -- Could NOT find FluidSynth (missing: FLUIDSYNTH_LIBRARIES FLUIDSYNTH_INCLUDE_DIR)
    -- Looking for filelength
    -- Looking for filelength - not found
    -- Looking for strupr
    -- Looking for strupr - not found
    -- Looking for stricmp
    -- Looking for stricmp - not found
    -- Looking for strnicmp
    -- Looking for strnicmp - not found
    -- Looking for clock_gettime in rt
    -- Looking for clock_gettime in rt - not found
    -- Looking for clock_gettime
    -- Looking for clock_gettime - found
    -- Performing Test HAS_VA_COPY
    -- Performing Test HAS_VA_COPY - Success
    CMake Warning at /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:554 (message):
      Imported targets and dependency information not available for Boost version
      (all versions older than 1.33)
    Call Stack (most recent call first):
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:894 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:1525 (_Boost_MISSING_DEPENDENCIES)
      src/vizdoom/src/CMakeLists.txt:559 (find_package)
    
    
    CMake Warning at /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:554 (message):
      Imported targets and dependency information not available for Boost version
      (all versions older than 1.33)
    Call Stack (most recent call first):
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:894 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:1525 (_Boost_MISSING_DEPENDENCIES)
      src/vizdoom/src/CMakeLists.txt:559 (find_package)
    
    
    CMake Warning at /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:554 (message):
      Imported targets and dependency information not available for Boost version
      (all versions older than 1.33)
    Call Stack (most recent call first):
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:894 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:1525 (_Boost_MISSING_DEPENDENCIES)
      src/vizdoom/src/CMakeLists.txt:559 (find_package)
    
    
    CMake Warning at /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:554 (message):
      Imported targets and dependency information not available for Boost version
      (all versions older than 1.33)
    Call Stack (most recent call first):
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:894 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:1525 (_Boost_MISSING_DEPENDENCIES)
      src/vizdoom/src/CMakeLists.txt:559 (find_package)
    
    
    CMake Error at /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:1902 (message):
      Unable to find the requested Boost libraries.
    
      Unable to find the Boost header files.  Please set BOOST_ROOT to the root
      directory containing Boost or BOOST_INCLUDEDIR to the directory containing
      Boost's headers.
    Call Stack (most recent call first):
      src/vizdoom/src/CMakeLists.txt:559 (find_package)
    
    
    -- Fluid synth libs: FLUIDSYNTH_LIBRARIES-NOTFOUND
    -- Found PythonInterp: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3 (found suitable version "3.6.2", minimum required is "3")
    -- Found PythonLibs: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin/libpython3.6.dylib (found suitable version "3.6.2", minimum required is "3.6")
    CMake Warning at /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:554 (message):
      Imported targets and dependency information not available for Boost version
      (all versions older than 1.33)
    Call Stack (most recent call first):
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:894 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:1525 (_Boost_MISSING_DEPENDENCIES)
      CMakeLists.txt:229 (find_package)
    
    
    CMake Warning at /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:1589 (message):
      No header defined for python-py36; skipping header check
    Call Stack (most recent call first):
      CMakeLists.txt:229 (find_package)
    
    
    CMake Warning at /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:554 (message):
      Imported targets and dependency information not available for Boost version
      (all versions older than 1.33)
    Call Stack (most recent call first):
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:894 (_Boost_COMPONENT_DEPENDENCIES)
      /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:1525 (_Boost_MISSING_DEPENDENCIES)
      CMakeLists.txt:234 (find_package)
    
    
    CMake Warning at /usr/local/Cellar/cmake/3.9.3_1/share/cmake/Modules/FindBoost.cmake:1589 (message):
      No header defined for python3; skipping header check
    Call Stack (most recent call first):
      CMakeLists.txt:234 (find_package)
    
    
    CMake Error at CMakeLists.txt:239 (MESSAGE):
      Could not find boost python3
    
    
    CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
    Please set them or make sure they are set and tested correctly in the CMake files:
    Boost_INCLUDE_DIR (ADVANCED)
       used as include directory in directory /tmp/pip-1xpigfnq-build
       used as include directory in directory /tmp/pip-1xpigfnq-build
       used as include directory in directory /tmp/pip-1xpigfnq-build
       used as include directory in directory /tmp/pip-1xpigfnq-build
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/jpeg-6b
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/jpeg-6b
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/jpeg-6b
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/game-music-emu
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/game-music-emu
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/game-music-emu/gme
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/game-music-emu/gme
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/game-music-emu/gme
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/lzma
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/lzma
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/lzma
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/tools
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/tools
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/tools/lemon
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/tools/lemon
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/tools/lemon
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/tools/re2c
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/tools/re2c
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/tools/re2c
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/tools/updaterevision
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/tools/updaterevision
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/tools/updaterevision
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/tools/zipdir
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/tools/zipdir
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/tools/zipdir
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/dumb
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/dumb
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/dumb
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/gdtoa
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/gdtoa
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/gdtoa
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/wadsrc
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/wadsrc
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/wadsrc
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/src
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/src
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/src
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/src
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/src
       used as include directory in directory /tmp/pip-1xpigfnq-build/src/vizdoom/src
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-1xpigfnq-build/CMakeFiles/CMakeOutput.log".
    See also "/tmp/pip-1xpigfnq-build/CMakeFiles/CMakeError.log".
    
    Installation failed, you may be missing some dependencies.
    Please check https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md for details
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-1xpigfnq-build/setup.py", line 111, in <module>
        keywords=['vizdoom', 'doom', 'ai', 'deep learning', 'reinforcement learning', 'research']
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/private/tmp/pip-1xpigfnq-build/setup.py", line 65, in run
        subprocess.check_call(['cmake'] + cmake_arg_list)
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_BUILD_TYPE=Release', '-DBUILD_PYTHON=ON', '-DPYTHON_LIBRARY=/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin/libpython3.6.dylib', '-DPYTHON_INCLUDE_DIR=/Library/Frameworks/Python.framework/Versions/3.6/include/python3.6m', '-DBUILD_PYTHON3=ON']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-1xpigfnq-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-7flo1mky-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-1xpigfnq-build/
```

**Comment by mwydmuch** [comment]
Hello @gastoncesarf,
it looks like your Boost version is too old, try to upgrade it.
Also, similar problem was discussed here: #243

**Comment by gastoncesarf** [comment]
Hello @mwydmuch, I tried with last version (1_65_X) but is not working too. There is a workaround in the issue (#243) that suggest not install the last version. So, I do not understand what is the problem or the solution? :D

**Comment by mwydmuch** [comment]
Old issue, related to old OS X and Boost version, closing.
