### ISSUE TITLE
Bug with GUI within Classes?

### ISSUE THREAD

**Issue by BJDev95** [Farama-Foundation/ViZDoom#294]
We have encountered the following problem using ViZDoom as a TensorForce environment.

**WHAT PERFECTLY WORKS:**
```
render = True
env = DoomGame()
env.set_doom_map("map01")
env.set_screen_resolution(ScreenResolution.RES_640X480) # 160X120
env.set_screen_format(ScreenFormat.GRAY8)
env.set_render_hud(render)
env.set_render_crosshair(render)
env.set_render_weapon(render)
env.set_render_decals(render)
env.set_render_particles(render)
env.add_available_button(Button.MOVE_LEFT)
env.add_available_button(Button.MOVE_RIGHT)
env.add_available_button(Button.ATTACK)
env.add_available_game_variable(GameVariable.AMMO2)
env.add_available_game_variable(GameVariable.POSITION_X)
env.add_available_game_variable(GameVariable.POSITION_Y)
env.set_episode_timeout(300)
env.set_episode_start_time(10)
env.set_window_visible(render)
env.set_sound_enabled(False)
env.set_living_reward(-1)
env.set_mode(Mode.PLAYER)
env.init()
```
**HOWEVER, the following lines fail:**
```
class Test():
    def __init__(self, render=True):

        env = DoomGame()
        env.set_doom_map("map01")
        env.set_screen_resolution(ScreenResolution.RES_640X480) # 160X120
        env.set_screen_format(ScreenFormat.GRAY8)
        env.set_render_hud(render)
        env.set_render_crosshair(render)
        env.set_render_weapon(render)
        env.set_render_decals(render)
        env.set_render_particles(render)
        env.add_available_button(Button.MOVE_LEFT)
        env.add_available_button(Button.MOVE_RIGHT)
        env.add_available_button(Button.ATTACK)
        env.add_available_game_variable(GameVariable.AMMO2)
        env.add_available_game_variable(GameVariable.POSITION_X)
        env.add_available_game_variable(GameVariable.POSITION_Y)
        env.set_episode_timeout(300)
        env.set_episode_start_time(10)
        env.set_window_visible(render)
        env.set_sound_enabled(False)
        env.set_living_reward(-1)
        env.set_mode(Mode.PLAYER)
        env.init()

environment = Test(render=True)
```
The problem: Starting of a graphical ViZDoom instance within a class fails with the following error:
```
Could not initialize SDL video:
No available video device

Traceback (most recent call last):
  File "test.py", line 62, in <module>
    environment = Test(render=True)
  File "test.py", line 31, in __init__
    env.init()
vizdoom.vizdoom.ViZDoomErrorException: Could not initialize SDL video:
No available video device
```
How can we fix this issue?

**Comment by mihahauke** [comment]
Well, you need to install sdl and have a display device if yout want to show the game in a window.

**Comment by BJDev95** [comment]
Of course sdl is installed and a display device is available. No virtual device, no Remote PC
Using Ubuntu 16.04 LTS

All demos of Vizdoom were working and if you have a look at the example above you see, it can't be installation problem, can it?

**Comment by mihahauke** [comment]
Sorry for rushed answer and treating you like someone less proficient than you seem to be. We will look into it soon, it's quite peculiar.

**Comment by Miffyli** [comment]
I was not able to replicate the issue (Ubuntu 16.04, Python 3.5, VizDoom 1.1.4) on a server with a display.
- No class (first code), Render=True, over SSH: "No display"
- Class (second code), Render=True, over SSH: "No display"
- No class, Render=False, over SSH: Works
- Second code, Render=False, over SSH: Works
- Render=False: Works on all configurations

**Comment by mwydmuch** [comment]
Old issue, closing.
