### ISSUE TITLE
install question and import error

### ISSUE THREAD

**Issue by tim54100** [Farama-Foundation/ViZDoom#406]
Hi, I follow the answer of the [issue178 ](https://github.com/mwydmuch/ViZDoom/issues/178).
I faced the error below like issue178 when typing the command "pip install -e ."
```
Command "/data2/home2/EastGeno/EastGeno_env/EastGeno_main/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-qede6hfa/vizdoom/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-8aa2lgcc/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-qede6hfa/vizdoom/
```
I also meet the problem, so I use the command ``` make -j 15 ``` when I finished Cmake.
I tried the ```make -j 4```,too. But It did't work.
```
subprocess.CalledProcessError: Command '['make', '-j', '15']' returned non-zero exit status 2
```
After the Cmake,make and copy, I get the error message below when i try to import vizdoom.
```
>>>from vizdoom import *
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```
This is Cmake command I used.
```
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON3=ON \
-DPYTHON_INCLUDE_DIR=/data2/home2/EastGeno/EastGeno_env/EastGeno_main/include/python3.6m \
-DPYTHON_LIBRARY=/data2/home2/EastGeno/EastGeno_env/EastGeno_main/lib/libpython3.6m.so \
-DPYTHON_EXECUTABLE=/data2/home2/EastGeno/EastGeno_env/EastGeno_main//bin/python3.6 \
-DNUMPY_INCLUDES=/data2/home2/EastGeno/EastGeno_env/EastGeno_main/lib/python3.6/site-packages/numpy/core/include
```
My enviroment is python3.6.8 in anaconda, Ubuntu16.04, and try to install the lastest vizdoom, github's version.

Did i do something wrong in installing vizdoom?

**Comment by Miffyli** [comment]
Can you post more, or all, of the error log? For now I can suggest trying `sudo pip install -e` (with the `sudo`). Sometimes this helps to pip-install vizdoom, but I am not sure what the damages are (if any).

**Comment by tim54100** [comment]
I tried the ```sudo pip install -e```. It installed the vizdoom with python2.7. I want to install vizdoom in the anaconda envrioment python3.6 .
```
Obtaining file:///data2/home2/EastGeno/RL/ViZDoom
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/lib/python2.7/dist-packages (from vizdoom===1.1.8)
Installing collected packages: vizdoom
  Running setup.py develop for vizdoom
Successfully installed vizdoom-1.1.8
```
Because I want to get the full error message, i removed the vizdoom package manually.
Weirdly, I retry the ``` pip install -e .```command. I installed successfully like ```sudo pip install -e .```, but i still can not import the module ```ModuleNotFoundError: No module named 'vizdoom'```

I don't know what happen and I temporarily can't get the full error message before.

**Comment by Miffyli** [comment]
You first have to activate the anaconda environment and then call `sudo pip install -e .` for it to install, otherwise it will install it to system's Python (I assume this happened as it installed it on Python2.7)

**Comment by tim54100** [comment]
Yup, I did activate the anaconda environment before I call ```sudo pip install -e .```. It still installed vizdoom to system's Python.
Below is the entire message.
```
(/data2/home2/EastGeno/EastGeno_env/EastGeno_main) nchuai@nchuai-server:/data2/home2/EastGeno/ViZDoom$ sudo pip install -e .
The directory '/home/nchuai/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/nchuai/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Obtaining file:///data2/home2/EastGeno/ViZDoom
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/lib/python2.7/dist-packages (from vizdoom===1.1.8)
Installing collected packages: vizdoom
  Running setup.py develop for vizdoom
Successfully installed vizdoom

```

**Comment by Miffyli** [comment]
Ah yes, `sudo` changes the environment variables so that it will use system pip instead of the environments pip. My bad.

You can fix this by explicitly providing bath to pip binary you want to run, i.e. the one inside the environment. I navigated next to my environment folder and then commanded `sudo ./conda-env/bin/pip install vizdoom` (environment is in `conda-env` directory). Seems to work correctly.

**Comment by tim54100** [comment]
I successfully installed the vizdoom.
```
(/data2/home2/EastGeno/EastGeno_env/EastGeno_main) nchuai@nchuai-server:/data2/home2/EastGeno/ViZDoom$ sudo /data2/home2/EastGeno/EastGeno_env/EastGeno_main/bin/pip install vizdoom
WARNING: The directory '/home/nchuai/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/nchuai/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting vizdoom
  Downloading https://files.pythonhosted.org/packages/2d/6c/23565c09387173423883e7881fce53541ff89b5209ca0904c67e577dd6ac/vizdoom-1.1.7.tar.gz (4.9MB)
     |████████████████████████████████| 4.9MB 242kB/s 
Requirement already satisfied: numpy in /data2/home2/EastGeno/EastGeno_env/EastGeno_main/lib/python3.6/site-packages (from vizdoom) (1.16.4)
Building wheels for collected packages: vizdoom
  Building wheel for vizdoom (setup.py) ... done
  Stored in directory: /home/nchuai/.cache/pip/wheels/67/98/04/d96d2c8edb8d1c008d926716257b407e56fb3ee0c81e51d25e
Successfully built vizdoom
Installing collected packages: vizdoom
Successfully installed vizdoom-1.1.7
```
But when I want to import the vizdoom, it still crashed.
```
(/data2/home2/EastGeno/EastGeno_env/EastGeno_main) nchuai@nchuai-server:/data2/home2/EastGeno/ViZDoom$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from vizdoom import *
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

**Comment by Miffyli** [comment]
Hm... I have not used Conda environments too much, but they install their own libraries if I am not terribly mistaken. Seems like the vizdoom is being compiled with different headers and then tries to use conda environment's libraries. One more trick I have is to try `sudo -E /data2/home2/EastGeno/EastGeno_env/EastGeno_main/bin/pip install vizdoom` to retain the environment variables (and hopefully the paths to libraries defined by conda).

**Comment by tim54100** [comment]
I tried the trick ```sudo -E /data2/home2/EastGeno/EastGeno_env/EastGeno_main/bin/pip install vizdoom``` When i import vizdoom,i get same error message.

Now, i can just call ```pip install vizdoom``` to successfully install vizdoom, but still can not import.
So I create a new anaconda environment to test, then i get new error message when importing vizdoom.
```
(/data2/home2/EastGeno/EastGeno_env/doom) nchuai@nchuai-server:/data2/home2/EastGeno$ pip install vizdoom
Collecting vizdoom
  Cache entry deserialization failed, entry ignored
Requirement already satisfied: numpy in /home/nchuai/anaconda3/lib/python3.6/site-packages (from vizdoom)
Installing collected packages: vizdoom
Successfully installed vizdoom-1.1.7
You are using pip version 9.0.1, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(/data2/home2/EastGeno/EastGeno_env/doom) nchuai@nchuai-server:/data2/home2/EastGeno$ python
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 13 2017, 12:02:49) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from vizdoom import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nchuai/anaconda3/lib/python3.6/site-packages/vizdoom/__init__.py", line 10, in <module>
    _this_python_version, _COMPILED_PYTHON_VERSION))
SystemError: This interpreter version: '3.6.3' doesn't match with version of the interpreter ViZDoom was compiled with: 3.6.8
```

**Comment by tim54100** [comment]
I figure out it's interpreter version wrong, so I recreate the anaconda environment with python3.6.8.
I get a new error message
```
(/data2/home2/EastGeno/EastGeno_env/doom) nchuai@nchuai-server:/data2/home2/EastGeno/EastGeno_env$ pip install vizdoom
Collecting vizdoom
Collecting numpy (from vizdoom)
  Using cached https://files.pythonhosted.org/packages/19/b9/bda9781f0a74b90ebd2e046fde1196182900bd4a8e1ea503d3ffebc50e7c/numpy-1.17.0-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: numpy, vizdoom
Successfully installed numpy-1.17.0 vizdoom-1.1.7
(/data2/home2/EastGeno/EastGeno_env/doom) nchuai@nchuai-server:/data2/home2/EastGeno/EastGeno_env$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vizdoom
*** Error in `python': corrupted size vs. prev_size: 0x000056005cd8d6b0 ***
Segmentation fault (core dumped)
```
I will still try to find the interpreter which compiled vizdoom.

**Comment by Miffyli** [comment]
Sounds like it is still using wrong headers and libraries to compile the vizdoom? Even if the Python headers/libraries match (the one you used to compile ViZDoom and the one used by conda env's python), I imagine some of the other libraries do not, hence you are getting an obscure runtime error. 

The core issue might be something with much deeper roots, making it hard to fix right though. See older discussions on ViZDoom failing with conda: #175 and #204

**Comment by tim54100** [comment]
It's ok.I am still thankful for your fast response(*^-^*).
I will temporarily use vizdoom with the system's python. I am aware of the system's python can import correctly.
```
nchuai@nchuai-server:/data2/home2/EastGeno$ sudo pip install vizdoom
[sudo] password for nchuai: 
The directory '/home/nchuai/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/nchuai/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting vizdoom
  Downloading https://files.pythonhosted.org/packages/2d/6c/23565c09387173423883e7881fce53541ff89b5209ca0904c67e577dd6ac/vizdoom-1.1.7.tar.gz (4.9MB)
    100% |████████████████████████████████| 4.9MB 232kB/s 
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/lib/python2.7/dist-packages (from vizdoom)
Installing collected packages: vizdoom
  Running setup.py install for vizdoom ... done
Successfully installed vizdoom-1.1.7
You are using pip version 8.1.1, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
nchuai@nchuai-server:/data2/home2/EastGeno$ sudo python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import vizdoom
>>> 
```

**Comment by mwydmuch** [comment]
Old issue, conda support was improved since then. Closing.
