### ISSUE TITLE
Cannot install on macOS

### ISSUE THREAD

**Issue by zhangfeifan21** [Farama-Foundation/ViZDoom#515]
I cannot install vizdoom on my mac, and I've installed all the dependencies listed, but the build cannot be done.
The logs are here:

Collecting git+https://github.com/mwydmuch/ViZDoom
  Cloning https://github.com/mwydmuch/ViZDoom to /private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-req-build-56a67vbb
  Running command git clone --filter=blob:none -q https://github.com/mwydmuch/ViZDoom /private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-req-build-56a67vbb
  Resolved https://github.com/mwydmuch/ViZDoom to commit e9db9b5679f064c5d499aafbc0d11c2d38f8a23d
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in ./opt/anaconda3/envs/doomlab/lib/python3.6/site-packages (from vizdoom==1.1.14) (1.19.5)
Building wheels for collected packages: vizdoom
  Building wheel for vizdoom (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/zhangyifei/opt/anaconda3/envs/doomlab/bin/python3.6 /Users/zhangyifei/opt/anaconda3/envs/doomlab/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/tmphbde2byz
       cwd: /private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-req-build-56a67vbb
  Complete output (107 lines):
  running bdist_wheel
  running build
  CMake Warning:
    No source or binary directory provided.  Both will be assumed to be the
    same as the current working directory, but note that this warning will
    become a fatal error in future CMake releases.
  
  
  -- The C compiler identification is AppleClang 13.1.6.13160021
  -- The CXX compiler identification is AppleClang 13.1.6.13160021
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found Boost: /Users/zhangyifei/opt/anaconda3/envs/doomlab/lib/cmake/Boost-1.76.0/BoostConfig.cmake (found suitable version "1.76.0", minimum required is "1.65.0") found components: filesystem thread system date_time chrono regex iostreams
  -- Found Threads: TRUE
  -- Found BZip2: /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib/libbz2.tbd (found version "1.0.8")
  -- Looking for BZ2_bzCompressInit
  -- Looking for BZ2_bzCompressInit - found
  -- Could NOT find JPEG (missing: JPEG_LIBRARY) (found version "80")
  -- Found ZLIB: /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib/libz.tbd (found version "1.2.11")
  -- Could NOT find GME (missing: GME_LIBRARIES GME_INCLUDE_DIR)
  -- Using system zlib
  -- Using internal jpeg library
  -- Using system bzip2 library
  -- Using internal gme library
  -- Looking for strdup
  -- Looking for strdup - found
  -- Looking for strndup
  -- Looking for strndup - found
  -- Looking for sys/types.h
  -- Looking for sys/types.h - found
  -- Looking for stdint.h
  -- Looking for stdint.h - found
  -- Looking for stddef.h
  -- Looking for stddef.h - found
  -- Check size of char
  -- Check size of char - done
  -- Check size of short
  -- Check size of short - done
  -- Check size of int
  -- Check size of int - done
  -- Check size of long
  -- Check size of long - done
  -- /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include
  -- /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include
  -- /private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-req-build-56a67vbb/src/vizdoom/lzma/C
  -- Looking for itoa
  -- Looking for itoa - not found
  -- Found PkgConfig: /opt/homebrew/bin/pkg-config (found version "0.29.2")
  CMake Error at /private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-vektfru1/overlay/lib/python3.6/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
    Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)
  Call Stack (most recent call first):
    /private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-vektfru1/overlay/lib/python3.6/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
    cmake_modules/FindSDL2.cmake:179 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
    src/vizdoom/src/CMakeLists.txt:200 (find_package)
  
  
  -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-req-build-56a67vbb/CMakeFiles/CMakeOutput.log".
  See also "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-req-build-56a67vbb/CMakeFiles/CMakeError.log".
  
  Installation failed, you may be missing some dependencies.
  Please check https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md for details
  
  Traceback (most recent call last):
    File "/Users/zhangyifei/opt/anaconda3/envs/doomlab/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/Users/zhangyifei/opt/anaconda3/envs/doomlab/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/zhangyifei/opt/anaconda3/envs/doomlab/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 262, in build_wheel
      metadata_directory)
    File "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-vektfru1/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 231, in build_wheel
      wheel_directory, config_settings)
    File "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-vektfru1/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-vektfru1/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 268, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-vektfru1/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 179, in <module>
      keywords=['vizdoom', 'doom', 'ai', 'deep learning', 'reinforcement learning', 'research']
    File "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-vektfru1/overlay/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/Users/zhangyifei/opt/anaconda3/envs/doomlab/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Users/zhangyifei/opt/anaconda3/envs/doomlab/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/Users/zhangyifei/opt/anaconda3/envs/doomlab/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-vektfru1/overlay/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/Users/zhangyifei/opt/anaconda3/envs/doomlab/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Users/zhangyifei/opt/anaconda3/envs/doomlab/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "setup.py", line 137, in run
      subprocess.check_call(cmake_arg_list)
    File "/Users/zhangyifei/opt/anaconda3/envs/doomlab/lib/python3.6/subprocess.py", line 291, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_BUILD_TYPE=Release', '-DBUILD_PYTHON=ON', '-DPYTHON_EXECUTABLE=/Users/zhangyifei/opt/anaconda3/envs/doomlab/bin/python3.6', '-DPYTHON_INCLUDE_DIR=/Users/zhangyifei/opt/anaconda3/envs/doomlab/include/python3.6m', '-DPYTHON_LIBRARY=/Users/zhangyifei/opt/anaconda3/envs/doomlab/lib/libpython3.6m.dylib']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for vizdoom
Failed to build vizdoom
ERROR: Could not build wheels for vizdoom, which is required to install pyproject.toml-based projects

**Comment by Miffyli** [comment]
Hey. I assume you are on M1 chips? Those have known to cause trouble. Check out this thread for potential tips: https://github.com/mwydmuch/ViZDoom/issues/485

**Comment by mwydmuch** [comment]
Hi @zhangfeifan21, thanks for opening the issue. First, the direct reason for your problem is that the building system (cmake) can't find the SDL2 library. Is it possible that you installed it in some custom way, e.g., in some custom location?
Can you check what is the output of `brew --prefix sdl2` command?

Second, this is not the direct reason for the error at this step, but will probably cause a compilation error later. We dropped the support for Python 3.6, since Pybind11 (the library we are using for Python bindings) also dropped support for it. Please update your Python version to at least 3.7 to use the newest version of ViZDoom.

**Comment by zhangfeifan21** [comment]
> Hi @zhangfeifan21, thanks for opening the issue. First, the direct reason for your problem is that the building system (cmake) can't find the SDL2 library. Is it possible that you installed it in some custom way, e.g., in some custom location? Can you check what is the output of `brew --prefix sdl2` command?
> 
> Second, this is not the direct reason for the error at this step, but will probably cause a compilation error later. We dropped the support for Python 3.6, since Pybind11 (the library we are using for Python bindings) also dropped support for it. Please update your Python version to at least 3.7 to use the newest version of ViZDoom.

I'll try to update python to 3.7, and it's `/opt/homebrew/opt/sdl2`

**Comment by zhangfeifan21** [comment]
I've updated python to 3.7 and modified the four lines in resampler.c but there's still an error.
The outputs are:
Processing /Users/zhangyifei/ViZDoom
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy
  Using cached numpy-1.21.6-cp37-cp37m-macosx_10_9_x86_64.whl (16.9 MB)
Building wheels for collected packages: vizdoom
  Building wheel for vizdoom (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for vizdoom (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [111 lines of output]
      running bdist_wheel
      running build
      CMake Warning:
        No source or binary directory provided.  Both will be assumed to be the
        same as the current working directory, but note that this warning will
        become a fatal error in future CMake releases.
      
      
      -- The C compiler identification is AppleClang 13.1.6.13160021
      -- The CXX compiler identification is AppleClang 13.1.6.13160021
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found Boost: /opt/homebrew/lib/cmake/Boost-1.79.0/BoostConfig.cmake (found suitable version "1.79.0", minimum required is "1.65.0") found components: filesystem thread system date_time chrono regex iostreams
      -- Found Threads: TRUE
      -- Found BZip2: /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib/libbz2.tbd (found version "1.0.8")
      -- Looking for BZ2_bzCompressInit
      -- Looking for BZ2_bzCompressInit - found
      -- Could NOT find JPEG (missing: JPEG_LIBRARY) (found version "80")
      -- Found ZLIB: /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/lib/libz.tbd (found version "1.2.11")
      -- Could NOT find GME (missing: GME_LIBRARIES GME_INCLUDE_DIR)
      -- Using system zlib
      -- Using internal jpeg library
      -- Using system bzip2 library
      -- Using internal gme library
      -- Looking for strdup
      -- Looking for strdup - found
      -- Looking for strndup
      -- Looking for strndup - found
      -- Looking for sys/types.h
      -- Looking for sys/types.h - found
      -- Looking for stdint.h
      -- Looking for stdint.h - found
      -- Looking for stddef.h
      -- Looking for stddef.h - found
      -- Check size of char
      -- Check size of char - done
      -- Check size of short
      -- Check size of short - done
      -- Check size of int
      -- Check size of int - done
      -- Check size of long
      -- Check size of long - done
      -- /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include
      -- /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include
      -- /Users/zhangyifei/ViZDoom/src/vizdoom/lzma/C
      -- Looking for itoa
      -- Looking for itoa - not found
      -- Found PkgConfig: /opt/homebrew/bin/pkg-config (found version "0.29.2")
      CMake Error at /private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-uf06ybf5/overlay/lib/python3.7/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find SDL2 (missing: SDL2_LIBRARY SDL2_INCLUDE_DIR)
      Call Stack (most recent call first):
        /private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-uf06ybf5/overlay/lib/python3.7/site-packages/cmake/data/CMake.app/Contents/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
        cmake_modules/FindSDL2.cmake:179 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
        src/vizdoom/src/CMakeLists.txt:200 (find_package)
      
      
      -- Configuring incomplete, errors occurred!
      See also "/Users/zhangyifei/ViZDoom/CMakeFiles/CMakeOutput.log".
      See also "/Users/zhangyifei/ViZDoom/CMakeFiles/CMakeError.log".
      
      Installation failed, you may be missing some dependencies.
      Please check https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md for details
      
      Traceback (most recent call last):
        File "/Users/zhangyifei/opt/anaconda3/envs/doomlab/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/zhangyifei/opt/anaconda3/envs/doomlab/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/zhangyifei/opt/anaconda3/envs/doomlab/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 262, in build_wheel
          metadata_directory)
        File "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-uf06ybf5/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 413, in build_wheel
          wheel_directory, config_settings)
        File "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-uf06ybf5/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-uf06ybf5/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 483, in run_setup
          self).run_setup(setup_script=setup_script)
        File "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-uf06ybf5/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 179, in <module>
        File "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-uf06ybf5/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-uf06ybf5/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-uf06ybf5/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-uf06ybf5/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-uf06ybf5/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-uf06ybf5/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-uf06ybf5/overlay/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-uf06ybf5/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-uf06ybf5/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
          super().run_command(command)
        File "/private/var/folders/y0/n_cj227x387fj_gkyl2973s80000gn/T/pip-build-env-uf06ybf5/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
          cmd_obj.run()
        File "<string>", line 137, in run
        File "/Users/zhangyifei/opt/anaconda3/envs/doomlab/lib/python3.7/subprocess.py", line 328, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_BUILD_TYPE=Release', '-DBUILD_PYTHON=ON', '-DPYTHON_EXECUTABLE=/Users/zhangyifei/opt/anaconda3/envs/doomlab/bin/python3.7', '-DPYTHON_INCLUDE_DIR=/Users/zhangyifei/opt/anaconda3/envs/doomlab/include/python3.7m', '-DPYTHON_LIBRARY=/Users/zhangyifei/opt/anaconda3/envs/doomlab/lib/libpython3.7m.dylib']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vizdoom
Failed to build vizdoom
ERROR: Could not build wheels for vizdoom, which is required to install pyproject.toml-based projects

**Comment by mwydmuch** [comment]
@zhangfeifan21, your SDL2 path confirms that you are using M1 Mac since `/opt/homebrew` is a path used for ARM packages. As @Miffyli wrote, it's difficult for us to support M1 Macs, since we don't own such machines at the moment, and M1 instances are not easily available. I'm sorry but you may need to fix a few things to make ViZDoom work on M1 Mac (if you figure that out, please make PR with your changes!)

Back to your error: the current build system is not searching for SDL2 in `/opt/homebrew`, you should edit `cmake_modules/FindSDL2.cmake` file and add this path, or as a workaround, you can set env. variable SDL2DIR to this path to hint the building system where exactly it should look for the SDL2 library.

**Comment by mwydmuch** [comment]
Support for Apple Silicon was added. Before proper release, it can be installed from the master using:
```
pip install git+https://github.com/mwydmuch/ViZDoom.git
```

I'm closing the issue.
