### ISSUE TITLE
Error in building VizDoom with anaconda environment (and sudo) with CMake 3.25 and Boost 1.70.

### ISSUE THREAD

**Issue by rxng8** [Farama-Foundation/ViZDoom#517]
### Issues

* description of an issue: Error in building VizDoom with anaconda environment (and sudo) with CMake 3.25 and Boost 1.70.
* ViZDoom version: currnent master branch,
* information about your OS platform, distribution and environment (GCC, Python, Java, Lua versions etc.): Ubuntu 22.04, python 3.8, anaconda3, using anaconda3 environment.
* Here is the log output when building with `pip install git+https://github.com/mwydmuch/ViZDoom.git`:

```
(py38) vn1747@gccis-vn1747-rl1:~/Desktop/vietlib$ pip install git+https://github.com/mwydmuch/ViZDoom.git
Collecting git+https://github.com/mwydmuch/ViZDoom.git
  Cloning https://github.com/mwydmuch/ViZDoom.git to /tmp/pip-req-build-rdbtubid
  Running command git clone --filter=blob:none --quiet https://github.com/mwydmuch/ViZDoom.git /tmp/pip-req-build-rdbtubid
  Resolved https://github.com/mwydmuch/ViZDoom.git to commit 7bacbe8287125137b53f66bbed7846ab56b002d2
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /home/vn1747/anaconda3/envs/py38/lib/python3.8/site-packages (from vizdoom==1.1.14) (1.23.5)
Building wheels for collected packages: vizdoom
  Building wheel for vizdoom (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for vizdoom (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [89 lines of output]
      running bdist_wheel
      running build
      CMake Warning:
        No source or binary directory provided.  Both will be assumed to be the
        same as the current working directory, but note that this warning will
        become a fatal error in future CMake releases.
      
      
      -- The C compiler identification is GNU 12.1.0
      -- The CXX compiler identification is GNU 12.1.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /home/vn1747/anaconda3/envs/py38/bin/x86_64-conda-linux-gnu-cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /home/vn1747/anaconda3/envs/py38/bin/x86_64-conda-linux-gnu-c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found Boost 1.70.0 at /home/vn1747/anaconda3/envs/py38/lib/cmake/Boost-1.70.0
      --   Requested configuration: QUIET REQUIRED COMPONENTS filesystem;thread;system;date_time;chrono;regex;iostreams
      -- Found boost_headers 1.70.0 at /home/vn1747/anaconda3/envs/py38/lib/cmake/boost_headers-1.70.0
      -- Found boost_filesystem 1.70.0 at /home/vn1747/anaconda3/envs/py38/lib/cmake/boost_filesystem-1.70.0
      -- No suitable boost_filesystem variant has been identified!
      --   libboost_filesystem.so.1.70.0 (shared, BUILD_SHARED_LIBS not ON, set Boost_USE_STATIC_LIBS=OFF to override)
      --   libboost_filesystem.a (static, Boost_USE_STATIC_LIBS=OFF)
      CMake Error at /home/vn1747/anaconda3/envs/py38/lib/cmake/Boost-1.70.0/BoostConfig.cmake:95 (find_package):
        Found package configuration file:
      
          /home/vn1747/anaconda3/envs/py38/lib/cmake/boost_filesystem-1.70.0/boost_filesystem-config.cmake
      
        but it set boost_filesystem_FOUND to FALSE so package "boost_filesystem" is
        considered to be NOT FOUND.  Reason given by package:
      
        No suitable build variant has been found.
      
      Call Stack (most recent call first):
        /home/vn1747/anaconda3/envs/py38/lib/cmake/Boost-1.70.0/BoostConfig.cmake:124 (boost_find_dependency)
        /tmp/pip-build-env-pl1lyf2z/overlay/lib/python3.8/site-packages/cmake/data/share/cmake-3.25/Modules/FindBoost.cmake:594 (find_package)
        CMakeLists.txt:101 (find_package)
      
      
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-req-build-rdbtubid/CMakeFiles/CMakeOutput.log".
      
      Installation failed, you may be missing some dependencies.
      Please check https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md for details
      
      Traceback (most recent call last):
        File "/home/vn1747/anaconda3/envs/py38/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/vn1747/anaconda3/envs/py38/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/vn1747/anaconda3/envs/py38/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-pl1lyf2z/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-pl1lyf2z/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-pl1lyf2z/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-pl1lyf2z/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 147, in <module>
        File "/tmp/pip-build-env-pl1lyf2z/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-pl1lyf2z/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-pl1lyf2z/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-pl1lyf2z/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-pl1lyf2z/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-pl1lyf2z/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-pl1lyf2z/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 325, in run
          self.run_command("build")
        File "/tmp/pip-build-env-pl1lyf2z/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-pl1lyf2z/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-pl1lyf2z/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 137, in run
        File "/home/vn1747/anaconda3/envs/py38/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_BUILD_TYPE=Release', '-DBUILD_PYTHON=ON', '-DPYTHON_EXECUTABLE=/home/vn1747/anaconda3/envs/py38/bin/python3.8', '-DPYTHON_INCLUDE_DIR=/home/vn1747/anaconda3/envs/py38/include/python3.8', '-DPYTHON_LIBRARY=/home/vn1747/anaconda3/envs/py38/lib/libpython3.8.so']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vizdoom
Failed to build vizdoom
ERROR: Could not build wheels for vizdoom, which is required to install pyproject.toml-based projects
```

**Comment by mwydmuch** [comment]
Hi @rxng8, thank you for opening the issue, I see similar issues reported in other C++/CMake repositories, seems to be a problem with this specific version of Boost 1.70, could you try to upgrade or downgrade it? Meanwhile, I will try to investigate and search for a better solution.

**Comment by mwydmuch** [comment]
Hi @rxng8, thank you once again for reporting this issue and creating the PR. As I explained in #518 I think this shouldn't be added permanently. Instead, I've added an easy way to apply this workaround when using `pip install`. Now you can pass additional cmake arguments to setup.py by `VIZDOOM_CMAKE_ARGS` environmental variable, to add this argument:
```
export VIZDOOM_CMAKE_ARGS='-DBoost_NO_BOOST_CMAKE=ON'
pip install git+https://github.com/mwydmuch/ViZDoom.git
```

I'm closing the issue for now.
