### ISSUE TITLE
python setup.py build failed in ARM64 machine

### ISSUE THREAD

**Issue by WendaDeng** [Farama-Foundation/ViZDoom#530]
### Issues
I wanted to install ViZDoom in my arm64 machine. But I can't use `pip install vizdoom` command directly. So, I was tring to build ViZDoom from source code using `python setup.py build` command. I used `master` branch of ViZDoom code and I installed all the necessary dependencies mentioned in the Building.md doc of ViZDoom. Unfortunately, I still can't build ViZDoom successfully. I was using docker to emulate arm platform in x86 machine. The docker image was build using `docker buildx build` command.

Information about my environment:
```
OS: 5.15.0-56-generic 20.04.1-Ubuntu x86_64 GNU/Linux
Docker version: 20.10.22
Miniconda version: 22.11.1-1
Python version: default 3.10.8, also try 3.11.0 by conda
GCC version: 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 
CMake version: default 3.16.3, also try 3.25.1
```

Output of `python setup.py build`:
```
running build
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.


-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost: /usr/lib/aarch64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.65.0") found components: filesystem thread system date_time chrono regex iostreams 
-- Found Threads: TRUE  
-- Found BZip2: /usr/lib/aarch64-linux-gnu/libbz2.so (found version "1.0.8") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found JPEG: /usr/lib/aarch64-linux-gnu/libjpeg.so (found version "80") 
-- Found ZLIB: /usr/lib/aarch64-linux-gnu/libz.so (found version "1.2.11") 
-- Could NOT find GME (missing: GME_INCLUDE_DIR) 
-- Using system zlib
-- Using system jpeg library
-- Using system bzip2 library
-- Using internal gme library
-- Performing Test HAVE_NO_ARRAY_BOUNDS
-- Performing Test HAVE_NO_ARRAY_BOUNDS - Success
-- Performing Test __LIBGME_TEST_VISIBILITY
-- Performing Test __LIBGME_TEST_VISIBILITY - Success
-- Looking for strdup
-- Looking for strdup - found
-- Looking for strndup
-- Looking for strndup - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of char
-- Check size of char - done
-- Check size of short
-- Check size of short - done
-- Check size of int
-- Check size of int - done
-- Check size of long
-- Check size of long - done
-- /usr/include
-- /usr/include
-- /root/ViZDoom/src/vizdoom/lzma/C
-- Looking for itoa
-- Looking for itoa - not found
-- Performing Test DUMB_CAN_USE_SSE
-- Performing Test DUMB_CAN_USE_SSE - Failed
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'gtk+-2.0'
--   Found gtk+-2.0, version 2.24.32
-- Found SDL2: /usr/local/lib/libSDL2main.a;/usr/local/lib/libSDL2.so;-lpthread  
-- Found OpenAL: /usr/lib/aarch64-linux-gnu/libopenal.so  
-- Could not find FMOD include files
-- Could NOT find SndFile (missing: SNDFILE_LIBRARY SNDFILE_INCLUDE_DIR) 
-- Could NOT find MPG123 (missing: MPG123_LIBRARIES MPG123_INCLUDE_DIR) 
-- Found FluidSynth: /usr/lib/aarch64-linux-gnu/libfluidsynth.so  
-- Looking for filelength
-- Looking for filelength - not found
-- Looking for strupr
-- Looking for strupr - not found
-- Looking for stricmp
-- Looking for stricmp - not found
-- Looking for strnicmp
-- Looking for strnicmp - not found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Performing Test HAS_VA_COPY
-- Performing Test HAS_VA_COPY - Success
-- Found Boost: /usr/lib/aarch64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found version "1.71.0") found components: thread system date_time chrono 
-- Fluid synth libs: /usr/lib/aarch64-linux-gnu/libfluidsynth.so
-- Found PythonInterp: /opt/miniconda3/envs/game/bin/python3.11 (found suitable version "3.11", minimum required is "3") 
-- Found PythonLibs: /opt/miniconda3/envs/game/lib/libpython3.11.so (found suitable version "3.11.0", minimum required is "3.11") 
-- Pybind11 submodule update
Submodule 'src/lib_python/pybind11' (https://github.com/pybind/pybind11) registered for path 'src/lib_python/pybind11'
Cloning into '/root/ViZDoom/src/lib_python/pybind11'...
Submodule path 'src/lib_python/pybind11': checked out '914c06fb252b6cc3727d0eedab6736e88a3fcb01'
-- pybind11 v2.9.2 
-- Found PythonInterp: /opt/miniconda3/envs/game/bin/python3.11 (found version "3.11") 
-- Found PythonLibs: /opt/miniconda3/envs/game/lib/libpython3.11.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /root/ViZDoom
[  0%] Building C object src/vizdoom/tools/updaterevision/CMakeFiles/updaterevision.dir/updaterevision.c.o
[  0%] Building C object src/vizdoom/lzma/CMakeFiles/lzma.dir/C/7zArcIn.c.o
[  0%] Building C object src/vizdoom/tools/lemon/CMakeFiles/lemon.dir/lemon.c.o
[  0%] Building CXX object CMakeFiles/libvizdoom_shared.dir/src/lib/ViZDoomConfigLoader.cpp.o
[  0%] Building CXX object CMakeFiles/libvizdoom_static.dir/src/lib/ViZDoomConfigLoader.cpp.o
[  0%] Building CXX object src/vizdoom/tools/re2c/CMakeFiles/re2c.dir/actions.cc.o
[  0%] Building CXX object src/vizdoom/game-music-emu/gme/CMakeFiles/gme.dir/Blip_Buffer.cpp.o
[  0%] Linking C executable ../../../../bin/updaterevision
[  0%] Built target updaterevision

......

[ 37%] Linking C static library libdumb.a
[ 37%] Built target dumb
[ 38%] Generating xlat_parser.c, xlat_parser.h
[ 38%] Generating sc_man_scanner.h
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault (core dumped)
make[2]: *** [src/vizdoom/src/CMakeFiles/vizdoom.dir/build.make:81: src/vizdoom/src/xlat_parser.c] Error 139
make[2]: *** Deleting file 'src/vizdoom/src/xlat_parser.c'
make[1]: *** [CMakeFiles/Makefile2:712: src/vizdoom/src/CMakeFiles/vizdoom.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 38%] Linking CXX shared module ../../bin/python3.11/vizdoom.cpython-311-aarch64-linux-gnu.so
[ 38%] Built target libvizdoom_python
make: *** [Makefile:91: all] Error 2

Installation failed, you may be missing some dependencies. 
Please check https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md for details

Traceback (most recent call last):
  File "/root/ViZDoom/setup.py", line 158, in <module>
    setup(
  File "/opt/miniconda3/envs/game/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/game/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/game/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/opt/miniconda3/envs/game/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/opt/miniconda3/envs/game/lib/python3.11/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/opt/miniconda3/envs/game/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/root/ViZDoom/setup.py", line 149, in run
    subprocess.check_call(['make', '-j', str(cpu_cores)])
  File "/opt/miniconda3/envs/game/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '7']' returned non-zero exit status 2.
```
I can't find useful infomation from the output log, so please help.

**Comment by mwydmuch** [comment]
Hi @WendaDeng! First, please note that we do not officially support ARM64 architecture at the moment (Apple Silicon is the expectation). So there is some probability that ViZDoom may not compile/work on ARM64, since it was not tested by us. But it seems not to be an issue here.

I don't understand why you can just use pip install on your ARM machine. But if I understand correctly, this process of using the X86_64 machine to build the ARM64 version in Docker is using Qemu, which is a machine emulator and virtualizer, and in your log, we can see that it crashes during compilation (`qemu: uncaught target signal 11 (Segmentation fault) - core dumped`). 

This might be entirely Qemu's bug we do not control. It seems that there is plenty of similar issues for other packages/software that people try to build this way. So at the moment, I'm not sure what can be done about that.

**Comment by WendaDeng** [comment]
Hi, @mwydmuch, thanks for replying! Your guess is right, We are using Qemu to run ARM64 docker on x86 machine. We also try to build ViZDoom on ARM64 machine directly, but encounter the same problem. Below is the log output:
```
[ 36%] Linking C static library libdumb.a
[ 36%] Built target dumb
[ 36%] Generating sc_man_scanner.h
[ 37%] Generating xlat_parser.c, xlat_parser.h
Segmentation fault (core dumped)
src/vizdoom/src/CMakeFiles/vizdoom.dir/build.make:79: recipe for target 'src/vizdoom/src/xlat_parser.c' failed
make[2]: *** [src/vizdoom/src/xlat_parser.c] Error 139
make[2]: *** Deleting file 'src/vizdoom/src/xlat_parser.c'
CMakeFiles/Makefile2:712: recipe for target 'src/vizdoom/src/CMakeFiles/vizdoom.dir/all' failed
make[1]: *** [src/vizdoom/src/CMakeFiles/vizdoom.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 37%] Linking CXX shared library bin/libvizdoom.so
[ 37%] Built target libvizdoom_shared
[ 38%] Linking CXX static library bin/libvizdoom.a
[ 38%] Built target libvizdoom_static
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

Installation failed, you may be missing some dependencies. 
Please check https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md for details

Traceback (most recent call last):
  File "/home/smart/ViZDoom/setup.py", line 158, in <module>
    setup(
  File "/home/smart/miniconda3/envs/game/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/home/smart/miniconda3/envs/game/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/smart/miniconda3/envs/game/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/smart/miniconda3/envs/game/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/smart/miniconda3/envs/game/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
    super().run_command(command)
  File "/home/smart/miniconda3/envs/game/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/smart/ViZDoom/setup.py", line 149, in run
    subprocess.check_call(['make', '-j', str(cpu_cores)])
  File "/home/smart/miniconda3/envs/game/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '191']' returned non-zero exit status 2.
```
Without information about Qemu, but other messages are the same.

We also try to use `pip install vizdoom` command directly on ARM64 machine, but got following output log:
```
  [ 36%] Linking C static library libdumb.a
  [ 36%] Built target dumb
  [ 37%] Generating xlat_parser.c, xlat_parser.h
  [ 37%] Generating sc_man_scanner.h
  Segmentation fault (core dumped)
  src/vizdoom/src/CMakeFiles/vizdoom.dir/build.make:79: recipe for target 'src/vizdoom/src/xlat_parser.c' failed
  make[2]: *** [src/vizdoom/src/xlat_parser.c] Error 139
  make[2]: *** Deleting file 'src/vizdoom/src/xlat_parser.c'
  CMakeFiles/Makefile2:712: recipe for target 'src/vizdoom/src/CMakeFiles/vizdoom.dir/all' failed
  make[1]: *** [src/vizdoom/src/CMakeFiles/vizdoom.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
  [ 38%] Linking CXX static library bin/libvizdoom.a
  [ 38%] Linking CXX shared library bin/libvizdoom.so
  [ 38%] Built target libvizdoom_static
  [ 38%] Built target libvizdoom_shared
  Makefile:90: recipe for target 'all' failed
  make: *** [all] Error 2
  
  Installation failed, you may be missing some dependencies.
  Please check https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md for details
  
  Traceback (most recent call last):
    File "/home/smart/.local/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/smart/.local/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/smart/.local/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 262, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-lnjm524l/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 231, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-lnjm524l/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-lnjm524l/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 268, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-lnjm524l/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 178, in <module>
      keywords=['vizdoom', 'doom', 'ai', 'deep learning', 'reinforcement learning', 'research']
    File "/tmp/pip-build-env-lnjm524l/overlay/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-lnjm524l/overlay/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "setup.py", line 137, in run
      subprocess.check_call(['make', '-j', str(cpu_cores)])
    File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['make', '-j', '191']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for vizdoom
Failed to build vizdoom
ERROR: Could not build wheels for vizdoom, which is required to install pyproject.toml-based projects
```
These error messages are the same with build from source code.

We found that the error is related to using the `lemon` tool to generate `xlat_parser` code. So, we tried to build the source code using debug mode and see what is wrong with the `lemon` tool. We encounter some problems in the building process, but we finally build the project suceeseefully and did not encounter the error related to the `lemon`. That is kind of embarrassing. 

Problems we encountered in the building process are following:
#### 1
```
/root/ViZDoom/src/vizdoom/src/d_main.cpp: In function 'void D_DoomInit()':
/root/ViZDoom/src/vizdoom/src/d_main.cpp:2229:15: error: '_FPU_EXTENDED' was not declared in this scope
 2229 |   cw = (cw & ~_FPU_EXTENDED) | _FPU_DOUBLE;
      |               ^~~~~~~~~~~~~
/root/ViZDoom/src/vizdoom/src/d_main.cpp:2229:32: error: '_FPU_DOUBLE' was not declared in this scope
 2229 |   cw = (cw & ~_FPU_EXTENDED) | _FPU_DOUBLE;
      |                                ^~~~~~~~~~~
```
We fixed it by commenting out the cmake command related to `FPU_CONTROL_DIR` in `src/vizdoom/src/CMakeLists.txt` file.
```
-	find_path( FPU_CONTROL_DIR fpu_control.h )
-	if( FPU_CONTROL_DIR )
-		include_directories( ${FPU_CONTROL_DIR} )
-		add_definitions( -DHAVE_FPU_CONTROL )
-	endif( FPU_CONTROL_DIR )
+	# find_path( FPU_CONTROL_DIR fpu_control.h )
+	# if( FPU_CONTROL_DIR )
+  	# 	include_directories( ${FPU_CONTROL_DIR} )
+	# 	add_definitions( -DHAVE_FPU_CONTROL )
+	# endif( FPU_CONTROL_DIR )
```

#### 2
```
/root/ViZDoom/src/vizdoom/src/p_spec.cpp:1282:4: error: narrowing conversion of '-1' from 'int' to 'char' [-Wnarrowing]
```
We fixed it by changing the type of `hexenScrollies[24][2]` from `static const char` to `static const signed char` in `src/vizdoom/src/p_spec.cpp` file.
```
-			static const char hexenScrollies[24][2] =
+			static const signed char hexenScrollies[24][2] =
```

#### 3
```
[100%] Built target pk3
[100%] Assembling pip package in /root/ViZDoom/build/bin/python3.10/pip_package
Required ViZDoom's resources do not exist. Aborting.
make[2]: *** [src/lib_python/CMakeFiles/python_pip_package.dir/build.make:71: src/lib_python/CMakeFiles/python_pip_package] Error 3
make[1]: *** [CMakeFiles/Makefile2:767: src/lib_python/CMakeFiles/python_pip_package.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```
We fixed it by copying `vizdoom` binary file from `vizdoomd` binary file under `bin` directory. And we also added one command `cp ${BOTS_PATH} ${SCENARIOS_DEST_DIR}` right after the command `mkdir -p ${SCENARIOS_DEST_DIR}` in `scripts/assemble_pip_package.sh` file.
```
 mkdir -p ${SCENARIOS_DEST_DIR}
+cp ${BOTS_PATH} ${SCENARIOS_DEST_DIR}
```

These fixes work and we can import vizdoom successfully in python program. But those fixes are too complex and not elegant. So we hope you can help us to find a better solution, thanks!

**Comment by mwydmuch** [comment]
Thank you @WendaDeng for the detailed explanation and investigation!

2. This was already reported in the old issue #336. Also, I checked other improved ZDoom forks, and they contain this fix. So without a doubt, it should be changed in ViZDoom too.

3. This is because you compiled in DEBUG mode. In this mode, exe name is changed to vizdoomd instead of just vizdoom. So this doesn't really require fixing.

1. I'm not sure if this is the best way of fixing this, so I need to investigate. Could you provide your docker image, so I could also try to build it?

**Comment by WendaDeng** [comment]
Thank you @mwydmuch for providing related information. Yes, we can our provide docker image. But right now our public docker repository encounter a problem, we can not pull the public docker without login docker repository. We have reported this problem to our docker service provider and waiting for their reply. So please wait for a while. We will provide our docker image once this problem is fixed. Thanks!

**Comment by WendaDeng** [comment]
Hi @mwydmuch, I'm glad to tell you that we have fixed the docker repository problem. Our docker image is `bj-sm-ai-registry.cn-beijing.cr.aliyuncs.com/smai-public/miniconda:ubuntu20.04-cpu`. We build it from official `ubuntu:20.04` docker image. And we change apt and pip source cause we are in China. We have backed up the original apt source file to `/etc/apt/sources.list.bk` so you can reuse it easily. We also install some basic softwares in the image, such as `cmake vim git g++ python3 python3-pip python3-distutils python3-dev python-is-python3`, etc. We install miniconda(version 22.11.1-1) in the image and the default python version is 3.10.8. To use it in x86 machine, you may need to pull `multiarch/qemu-user-static:latest` docker image first.

**Comment by WendaDeng** [comment]
Hey @mwydmuch, is the docker image we provided available? Is there any progress?

**Comment by mwydmuch** [comment]
Hi @WendaDeng, I’m sorry, due to the ICML deadline in January and the vacations I’m on right now I haven't yet delve into it enough. But I remember about it, and should definitely work on the last weak of February. We aim to provide full ARM support in the feature so this is a priority for me.

**Comment by mwydmuch** [comment]
Hi @WendaDeng, I want to thank you for all the effort you put into this issue. It took some time, but I fixed all the issues, in the PR referenced above, soon it will be merged and we will do the next official release.

**Comment by WendaDeng** [comment]
Hi @mwydmuch, I want to thank you for your effort and help too. I'm going to try the new feature and tell you if it work for me. Thanks again.
